# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    dynamodb_table = "tf-alfresco-dev-lock-table"
    encrypt        = true
    key            = "peering-connection/terraform.tfstate"
    region         = "eu-west-2"
    bucket         = "tf-alfresco-dev-remote-state"
  }
}
